-- Таблица "Газета"
CREATE TABLE Newspaper (
                           NewspaperID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Идентификатор газеты (PK, автоинкремент)
                           Name VARCHAR(20) NOT NULL,                -- Название газеты
                           IndexEdition VARCHAR(20) NOT NULL UNIQUE,      -- Индекс издания (уникальный)
                           Editor VARCHAR(40) NOT NULL,                -- ФИО редактора
                           Price DECIMAL(10, 2) NOT NULL                 -- Цена экземпляра
);

-- Таблица "Типография"
CREATE TABLE PrintingHouse (
                               PrintingHouseID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Идентификатор типографии (PK, автоинкремент)
                               Name VARCHAR(20) NOT NULL,                   -- Название типографии
                               Address VARCHAR(50)                          -- Адрес типографии
);

-- Таблица "ПочтовоеОтделение"
CREATE TABLE PostOffice (
                            PostOfficeID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Идентификатор почтового отделения (PK, автоинкремент)
                            Number VARCHAR(20) NOT NULL UNIQUE,            -- Номер почтового отделения (уникальный)
                            Address VARCHAR(50)                           -- Адрес почтового отделения
);

-- Таблица "Тираж" (связывает газеты и типографии)
CREATE TABLE PrintRun (
                          PrintRunID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Идентификатор тиража (PK, автоинкремент)
                          NewspaperID INT NOT NULL,                    -- ID газеты (FK)
                          PrintingHouseID INT NOT NULL,                -- ID типографии (FK)
                          Quantity INT NOT NULL,                       -- Тираж (количество экземпляров)
                          FOREIGN KEY (NewspaperID) REFERENCES Newspaper(NewspaperID),
                          FOREIGN KEY (PrintingHouseID) REFERENCES PrintingHouse(PrintingHouseID)
);

-- Таблица "Поставка" (связывает тиражи и почтовые отделения)
CREATE TABLE Delivery (
                          DeliveryID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- Идентификатор поставки (PK, автоинкремент)
                          PrintRunID INT NOT NULL,                      -- ID тиража (FK)
                          PostOfficeID INT NOT NULL,                    -- ID почтового отделения (FK)
                          Quantity INT NOT NULL,                        -- Количество экземпляров в поставке
                          FOREIGN KEY (PrintRunID) REFERENCES PrintRun(PrintRunID),
                          FOREIGN KEY (PostOfficeID) REFERENCES PostOffice(PostOfficeID)
);